version: '3'
services:
    api:
        image: node:11.15.0
        restart: unless-stopped
        ports:
            - 4000:4000
        working_dir: '/app'
        volumes:
            - ./:/app
        command: 'npm run serve'
        networks:
            - net
    mysql:
        image: mysql:5.7
        volumes:
            - ./docker/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - net
    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
        ports:
            - 8080:80
        networks:
            - net
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8090:8080
        networks:
            - net
networks:
    net:
        driver: bridge
# docker-compose exec api /bin/bash
